name : print hello world
on :
  workflow_dispatch:
jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: print welcome message 
        run: echo "welcome to first workflow"
      - name: checkout the repo 
        uses: actions/checkout@v5.0.0
      - name: fetch all files
        run: ls -la
         
